favicon: null
name: christopherpalacios
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 1
  brandStrength: 0.8330523
  lightness: 0.2984823
  brandColors:
    - '#3044B3'
    - '#FFC6CF'
    - '#E9669A'
    - '#E03939'
    - '#B4426E'
  rhythmicContrast: 1
typography_spectrum: 0.648398
layout_spectrum: 0
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
