name: christopherpalacios
favicon: null
layout_spectrum: 0.62035
typography_spectrum: 0.4009
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3044B3'
    - '#FFC6CF'
    - '#E9669A'
    - '#E03939'
    - '#B4426E'
  brandStrength: 0.5625
  lightness: 0.6875
  saturation: 0.5625
  rhythmicContrast: 1
purpose: []
