name: christopher palacios
favicon: null
layout_spectrum: 0.3684
typography_spectrum: 0.41248
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Christopher Palacios
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-77282456-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#784B40'
    - '#01BBD7'
    - '#C7DE16'
    - '#2E48AC'
    - '#FC4230'
  brandStrength: 0.6875
  lightness: 0.8125
  saturation: 0.8125
  rhythmicContrast: 1
purpose: []
