name: christopherpalacios
favicon: null
layout_spectrum: 0.35767
typography_spectrum: 0.4009
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#80cbc4'
    - '#000000'
    - '#e0f2f1'
    - '#78909c'
    - '#4b5a61'
  brandStrength: 0.5625
  lightness: 0.625
  saturation: 0.375
  rhythmicContrast: 1
purpose: []
