analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.5050125
  brandStrength: 0.4047619
  lightness: 0.8402256
  brandColors:
    - '#3044B3'
    - '#FFC6CF'
    - '#E9669A'
    - '#E03939'
    - '#B4426E'
  rhythmicContrast: 0.7393484
typography_spectrum: 0.4354637
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.5595238
favicon: null
name: christopherpalacios
