name: christopherpalacios
favicon: null
layout_spectrum: 0.4098062419798225
typography_spectrum: 0.9157210080884397
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.3721323919016868
  lightness: 0.7801267791073769
  saturation: 0.6812901098746806
  rhythmicContrast: 0.867416976718232
purpose: []
